# -*- coding: utf-8 -*-
"""Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Cau1:
import pandas as pd

df = pd.read_csv("dulieuxettuyendaihoc.csv")

cat_cols = ['GT', 'DT', 'KV', 'KT']

quantitative = [c for c in df.columns
                if c not in cat_cols and pd.api.types.is_numeric_dtype(df[c])]

qualitative = [c for c in df.columns if c in cat_cols]

print("Định lượng:", quantitative)
print("Định tính:", qualitative)

#Cau2:
import pandas as pd

df = pd.read_csv("dulieuxettuyendaihoc.csv")

scale = {c: "Khoảng (Interval)" for c in df.columns}
scale.update({
    'GT': "Danh nghĩa (Nominal)",
    'DT': "Danh nghĩa (Nominal)",
    'KT': "Danh nghĩa (Nominal)",
    'KV': "Thứ bậc (Ordinal)"
})

pd.DataFrame(scale.items(), columns=["Tên biến", "Thang đo"])

#Cau3:
import pandas as pd
df = pd.read_csv("dulieuxettuyendaihoc.csv")
print("10 dòng đầu:")
print(df.head(10))
print("\n10 dòng cuối:")
print(df.tail(10))

#Cau4:
import pandas as pd
df = pd.read_csv("dulieuxettuyendaihoc.csv")
print("Số giá trị thiếu DT:", df['DT'].isna().sum())
print("\nBảng tần số DT:")
print(df['DT'].value_counts(dropna=False))
print("\nBảng tần suất DT:")
print(df['DT'].value_counts(normalize=True, dropna=False))
print("\nSố giá trị DT riêng biệt:", df['DT'].nunique(dropna=False))
df['DT'] = df['DT'].fillna(0)
print("\nSau khi điền, số giá trị thiếu DT:", df['DT'].isna().sum())

#Cau5:
import pandas as pd
df = pd.read_csv("dulieuxettuyendaihoc.csv")
print("Số giá trị thiếu T1:", df['T1'].isna().sum())
print("\nBảng tần số T1:")
print(df['T1'].value_counts(dropna=False))
print("\nBảng tần suất T1:")
print(df['T1'].value_counts(normalize=True, dropna=False))
mean_T1 = df['T1'].mean()
df['T1'] = df['T1'].fillna(mean_T1)

print("\nGiá trị Mean của T1:", mean_T1)
print("Sau khi điền, số giá trị thiếu T1:", df['T1'].isna().sum())

#Cau6:
import pandas as pd
df = pd.read_csv("dulieuxettuyendaihoc.csv")
score_cols = [c for c in df.columns
              if c not in ['GT', 'DT', 'KV', 'KT'] and pd.api.types.is_numeric_dtype(df[c])]
for col in score_cols:
    if df[col].isna().sum() > 0:
        mean_val = df[col].mean()
        df[col] = df[col].fillna(mean_val)
        print(f"{col}: điền {mean_val:.2f}")

print("\nTổng số dữ liệu thiếu còn lại:", df.isna().sum().sum())

#Cau7:
import pandas as pd
df = pd.read_csv("dulieuxettuyendaihoc.csv")
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] +
              df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] +
              df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] +
              df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10
print(df[['TBM1', 'TBM2', 'TBM3']].head())

#Cau8:
def xep_loai(tbm):
    if tbm < 5:
        return 'Y'
    elif tbm < 6.5:
        return 'TB'
    elif tbm < 8:
        return 'K'
    elif tbm < 9:
        return 'G'
    else:
        return 'XS'

df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)

print(df[['XL1', 'XL2', 'XL3']].head())

#Cau9:
for i in [1, 2, 3]:
    col = f'TBM{i}'
    df[f'US_TBM{i}'] = (df[col] - df[col].min()) / (df[col].max() - df[col].min()) * 4

print(df[['US_TBM1', 'US_TBM2', 'US_TBM3']].head())

#Cau10:
def xet_tuyen(row):
    if row['KT'] in ['A', 'A1']:
        diem = (row['DH1']*2 + row['DH2'] + row['DH3']) / 4
    elif row['KT'] == 'B':
        diem = (row['DH1'] + row['DH2']*2 + row['DH3']) / 4
    else:
        diem = (row['DH1'] + row['DH2'] + row['DH3']) / 3
    return 1 if diem >= 5 else 0

df['KQXT'] = df.apply(xet_tuyen, axis=1)

print(df[['KT', 'DH1', 'DH2', 'DH3', 'KQXT']].head())

#Cau11:
df.to_csv("processed_dulieuxettuyendaihoc.csv", index=False)